version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - 56720:5672
      - 15672:15672
  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=docker
    ports:
      - "54320:5432"
  api:
    build:
      context: .
      dockerfile: apps/api/.Dockerfile
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - "8080:8080"
    environment:
      - QUEUE_NAME=CompanyStatsQueue
      - QUEUE_URL=amqp://admin:admin@rabbitmq:5672
      - HTTP_PORT=8080
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=docker
      - DB_PASSWORD=docker
      - DB_NAME=docker
  visdemo:
    build:
      context: .
      dockerfile: apps/visdemo/.Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080

  datafeed0:
    build:
      context: .
      dockerfile: apps/datafeed0/.Dockerfile
    depends_on:
      - rabbitmq
    ports:
      - "8081:8081"
    environment:
      - QUEUE_NAME=CompanyStatsQueue
      - QUEUE_URL=amqp://admin:admin@rabbitmq:5672
      - HTTP_PORT=8081
