version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - 56720:5672
      - 15672:15672
  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=docker
    ports:
      - "54320:5432"
  api:
    build:
      context: .
      dockerfile: apps/api/.Dockerfile
#    command: ["./wait-for-it.sh", "postgres:5432", "--", "npm", "run", "start"]
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - "8081:8080"
    environment:
      - QUEUE_NAME=CompanyStatsQueue
      - QUEUE_URL=amqp://admin:admin@rabbitmq:5672
      - HTTP_PORT=8080
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=docker
      - DB_PASSWORD=docker
      - DB_NAME=docker
#  datafeed0:
#    build:
#      context: .
#      dockerfile: apps/datafeed0/.Dockerfile
##    command: ["./wait-for-it.sh", "postgres:5432", "--", "npm", "run", "start"]
##    depends_on:
##      - postgres
##      - rabbitmq
#    environment:
#      - QUEUE_NAME=CompanyStatsQueue
#      - QUEUE_URL=amqp://admin:admin@localhost:56720
#      - HTTP_PORT=8081
#
##    links:
##      - postgres
##      - rabbitmq
