import './global.css';
import { Layout } from '@xemida/ui';
import React from 'react';
import { ReactQueryProvider } from './providers/ReactQueryProvider';
import Link from 'next/link';

export const metadata = {
  title: 'Welcome to visdemo',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Layout>
          <Layout.Topmenu>
            <div className="ml-[20px] tracking-[6px]">XEMIDA.</div>
          </Layout.Topmenu>
          <ReactQueryProvider><Layout.Workspace>{children}</Layout.Workspace></ReactQueryProvider>
        </Layout>
      </body>
    </html>
  );
}
