/**
 * Generated by @openapi-codegen
 *
 * @version 1.0
 */
import type * as Fetcher from "./serverFetcher";
import { serverFetch } from "./serverFetcher";
import type * as Schemas from "./visdemoSchemas";

export type GetCompaniesError = Fetcher.ErrorWrapper<undefined>;

export type GetCompaniesResponse = Schemas.CompanyPresenter[];

export const getCompanies = (signal?: AbortSignal) =>
  serverFetch<GetCompaniesResponse, GetCompaniesError, undefined, {}, {}, {}>({
    url: "/company",
    method: "get",
    signal,
  });

export const operationsByTag = { company: { getCompanies } };
